### PR TITLE
chore: add eslint, styling checks, and enforce via husky

### PR DESCRIPTION
**Pull request by TillaTheHun0**
This PR:
- adds necessary eslint plugins (eslint was already added)
- runs `eslint --fix` to autofix linting issues
- manually update files to adhere to linting or comment an exception to the rule (ie. global fetch)
- enforce linting via `lint-staged` and `husky` `pre-commit` hook
- enforces `package.json` key order via `lint-staged` and `husky` `pre-commit` hook
- remove unused lockfiles across the repo

**no functionality should be changed as part of this PR**

I attempted to keep the linting as "non-custom" as possible by minimizing eslint plugins used. Later on, we might revisit this ie. lint order of dependencies in files, or even linting `package.json`s to to be in a consistent order.

Some files, I wasn't sure on whether we wanted to remove the unused variables, as I think they are being used to demonstrate the contract of the service/adapter. Instead of that, we should use jsdoc and module types, eventually. I will create an issue to track revisiting those instances where I disabled linting rules and to resolve them where applicable. Would be good first issue for a contributor, I think.

### CODE REVIEW

**Review by tripott — APPROVED** [review]

**Comment by TillaTheHun0** [comment]
The `adapter-fs` tests seem to have been broken for [a while](https://github.com/hyper63/hyper63/actions/workflows/tests-adapter-fs.yml). I think we should revisit those tests in a separate PR. Thoughts @tripott

**Comment by TillaTheHun0** [comment]
Also, it looks like there are per adapter github actions that publish to `npm` when it's package is changed on `main`. Perhaps this PR needs to contain version bumps for each adapter? Perhaps it's a good idea to add something `lerna` sooner rather than later to automate bumping versions across packages. 🤔

**Comment by tripott** [comment]
@TillaTheHun0 Yes, auto semver bumps would be good.

**Comment by TillaTheHun0** [comment]
I am going to manually bump the version of each adapter for now, until we can all meet to discuss what sort of tooling we want to us for automatically bumping versions.

I will do this as a single commit on the tip of this branch.

**Review by twilson63 — APPROVED** [review]

**Comment by TillaTheHun0** [comment]
bumped versions in 9945043

**Pull request merged**
